### ISSUE TITLE
stdout redirection seems broken

### ISSUE THREAD

**Issue by jdv** [lizmat/App-Rak#10]
jdv@jdv-lap:~/rakudo$ time rak role
...
This type cannot unbox to a native integer: P6opaque, Scalar
  in sub want-lines at /home/jdv/rakudo/install/share/perl6/site/sources/15066A5E79B965690BA65EFE60430F617F71BC47 (App::Rak) line 991
  in sub rak at /home/jdv/rakudo/install/share/perl6/site/sources/15066A5E79B965690BA65EFE60430F617F71BC47 (App::Rak) line 609
  in block <unit> at /home/jdv/rakudo/install/share/perl6/site/resources/0FFDA62CBE59FDD572FDAC1C05E0FDEB24029390 line 4
  in sub MAIN at /home/jdv/rakudo/install/share/perl6/site/bin/rak line 3
  in block <unit> at /home/jdv/rakudo/install/share/perl6/site/bin/rak line 1

real	0m2.199s
user	0m3.718s
sys	0m0.329s
jdv@jdv-lap:~/rakudo$

meanwhile

jdv@jdv-lap:~/rakudo$ time rak role > /dev/null

real	0m16.807s
user	0m23.311s
sys	0m1.240s
jdv@jdv-lap:~/rakudo$

**Comment by lizmat** [comment]
This is actually the same bug in spesh  :-(

Thanks for the report, though!
