### ISSUE TITLE
Incorrect option type for --sep 

### ISSUE THREAD

**Issue by Zer0-Tolerance** [lizmat/App-Rak#26]
Hi Liz,
Small bug when trying to set a different field separator in CSV file:
```
rak --csv-per-line --sep=';' '{ .say }' /tmp/file.csv
'--sep' can only be specified as a flag.
```

**Comment by lizmat** [comment]
Thanks for the headsup!

Fixed with https://github.com/lizmat/App-Rak/commit/32cbfc83bd

Also affected were `--quote` / `--escape`
