### ISSUE TITLE
--unique option is not being handled for CSV files

### ISSUE THREAD

**Issue by Zer0-Tolerance** [lizmat/App-Rak#29]
Hi liz,
another small bug with CSV and --unique ,I've applied my own patch to parsed CSV as array of hashes: 
```
rak --csv-per-line '{ .<a> }' /tmp/test.csv -u
The --unique option is not being handled and will be ignored.
If you believe this to be incorrect, please report an issue with
https://github.com/lizmat/App-Rak/issues/new .

../../../../tmp/test.csv
1:1
2:4
3:1
```
while it's working for JSON:
``` 
rak --json-per-line '{ .<ip_str> }' /tmp/a.json -u
101.43.51.104
```

**Comment by lizmat** [comment]
could you post the CSV file you use?

**Comment by Zer0-Tolerance** [comment]
sure:
```
cat /tmp/test.csv
a,b,c,d
1,2,3,4
4,3,2,1
1,2,3,4
```

**Comment by Zer0-Tolerance** [comment]
to me it's just about options compatibility rather than about CSV content, it seems `--unique` is only compatible for JSON in the current code ?

**Comment by lizmat** [comment]
`--unique` should work with any source.  E.g. a pattern like `'*.words.Slip'`

**Comment by Zer0-Tolerance** [comment]
ok then the behavior is not consistent between JSON and CSV hence the error message saying it 's not handled. I've looked at the code but I don't find the relevant code to produce unique items.

**Comment by lizmat** [comment]
Probably, haven't looked at it yet.  Wanted to push a release that will by default only look at actual text files, rather than by a set of known extensions.  The latter confused a lot of people, and in hindsight, I don't blame them  :-)

**Comment by lizmat** [comment]
It will probably be tomorrow: already did the weekly today, and two releases and other associated stuff.  Going to have dinner in a mo, and then probably zonk out for the rest of the day  :-)

But please keep those issues coming  :-)

**Comment by Zer0-Tolerance** [comment]
hehe sure thing, regarding the by default looking at only text file why not but you'll have to use `Filetype::Magic` to guess if it's text. It's good to be able to search in binary file as well for utf16 strings (_we're off topic a bit_).

**Comment by lizmat** [comment]
It's actually using `path-utils`'s `is-text` function

**Comment by lizmat** [comment]
Finally getting to it.  Note that:

`rak --csv-per-line '{ .<a> }'`

will never work, as `$_` is an array, not a hash inside the pattern

**Comment by Zer0-Tolerance** [comment]
> Finally getting to it. Note that:
> 
> `rak --csv-per-line '{ .<a> }'`
> 
> will never work, as `$_` is an array, not a hash inside the pattern

it's working for me because I've applied the patch to get each line as a hash.
