### ISSUE TITLE
The --find option throws warnings without "human" set to True

### ISSUE THREAD

**Issue by 2colours** [lizmat/App-Rak#31]
Hello,

I came across this issue while combining `rak` with my own text processing. Thanks to the talkative traces, I found the problem: the `$only-first` variable stays undefined when the "human" option is on False (either due to --no-human or no tty attached), however, find still relies on that, instead of `$stop-after` which is used everywhere else.

I think it's really only that; perhaps I can make a PR for it soon but it irked me enough to note it right now. :P

**Comment by lizmat** [comment]
Good catch!  Indeed, that was the problem.  Fixed in the next release!

**Comment by lizmat** [comment]
Fixed with https://github.com/lizmat/App-Rak/commit/8bcf1d0a3d
