### ISSUE TITLE
Should --/break be assumed when using --/show-file-name --matches-only --/show-item-number?

### ISSUE THREAD

**Issue by FCO** [lizmat/App-Rak#36]
https://irclogs.raku.org/raku/2022-11-29.html#14:27

**Comment by lizmat** [comment]
Looking at this command, are you sure you don't actually want `--unique`  or `--frequencies` ?

**Comment by lizmat** [comment]
Ok, I have slept on it, and for now I think it would be too magical to assume this.  Remember, you can always create a personal shortcut for what you want!  So I'm going to close this issue now.  Please re-open if you disagree.
