### ISSUE TITLE
Highlighting with regex

### ISSUE THREAD

**Issue by Zer0-Tolerance** [lizmat/App-Rak#37]
Hi Liz,
Another small bug, it seems that Rak is not using the highlighting when you use a file containing regex pattern:
`rak --ignore-case  --type=regex --patterns-from-file=/path/regex.txt /path/to_search`

can you have a look ?

**Comment by lizmat** [comment]
Thanks for the headsup.

I'm a bit busy this week with blog posts and rakuast related stuff.  I intend to get back to more App::Rak stuff when all of that is out of the way, but I suspect that may actually not be before Christmas. Unless I have a brainwave that tells me it is a one line change before that  :-)

**Comment by Zer0-Tolerance** [comment]
re-up

**Comment by lizmat** [comment]
I cannot reproduce this anymore.  Could you please verify this is fixed?

**Comment by Zer0-Tolerance** [comment]
it seems to be fixed.  Thanks a lot !
