### ISSUE TITLE
Parent directory (non-)findings

### ISSUE THREAD

**Issue by antononcube** [lizmat/App-Rak#44]
I expect this command to find files in the parent directory (at this point, it lists files in the current directory that have names that include ".."):  

```
rak --find ..
```

I expect this command to give directories in the parent directory (at this point, gives nothing):

```
 rak --find --dir .. 
```

------

For comparison, this works as expected: 

```
rak --find --dir .
```

**Comment by lizmat** [comment]
The first positional argument is always taken as the pattern to search for.  And if no path is specified, the current directory will be assumed.

So `rak --find ..` **will** search for files with `..` in their paths.

What you probably wanted is `rak --find --paths=..`

Closing as this *is* a bit of a WAT, but that's always the case with a lot of other DWIMs.
