### ISSUE TITLE
Option to include the first line of any searched file in the output

### ISSUE THREAD

**Issue by MasterDuke17** [lizmat/App-Rak#45]
I'm frequently searching CSV files with 20-30 columns, and when there's a hit it can be hard to know what the columns are. An option to print the first line of a file (either always, or only if that file had a match to the pattern) in addition to any hits would be nice.

**Comment by lizmat** [comment]
Are you using `--cvs-per-line` for this?

In other words: I guess you'd only want the first line if it *is* a CSV file, right?

Or are you searching pure on text?

**Comment by MasterDuke17** [comment]
I didn't know about/wasn't using `--csv-per-line`. I guess I generally know it's they're CSV files, but for some reason I'm thinking of the print-first-line as a general option.

**Comment by lizmat** [comment]
Then I guess you'd only want that printed *if* there is actually a match anywhere in the  file.  Not just for all files that are being searched, right?

**Comment by lizmat** [comment]
How about a `--accept-first[=N]` option.  This would accept the first N lines as matches (with N being `1` if specified as a flag).

This would then always show the first line of any file inspected.

**Comment by MasterDuke17** [comment]
Yep, that's pretty much exactly what I was thinking.

**Comment by lizmat** [comment]
Implemented with [0.3.9](https://raku.land/zef:lizmat/App::Rak/changes?v=0.3.9) so closing
