### ISSUE TITLE
Issue upgrading

### ISSUE THREAD

**Issue by MorayMySoc** [lizmat/App-Rak#46]
I'm getting the error:
```Failed to find dependencies: JSON::Fast:ver<0.19>:auth<cpan:TIMOTIMO>```
when trying:
```zef upgrade App::Rak```
Doing:
```zef search JSON::Fast```
Doesn't show a version 0.19 of JSON::Fast
```rak --version```
rak - provided by App::Rak 0.2.17, running Raku 6.d with Rakudo 2022.12

**Comment by lizmat** [comment]
https://raku.land/cpan:TIMOTIMO/JSON::Fast shows JSON::Fast to be at 0.19 ?

**Comment by MorayMySoc** [comment]
Must be an issue with my setup. Will have to have a deeper look - just goes to 0.17 in my zef search

![image](https://github.com/lizmat/App-Rak/assets/87022664/62140e5a-28cf-4563-8d38-a64642c8fc09)

**Comment by lizmat** [comment]
What does `zef install --verbose 'JSON::Fast:auth<cpan:TIMOTIMO>:ver<0.19>'` say?

**Comment by lizmat** [comment]
Also perhaps: `zef uninstall JSON::Fast` and then try installing it again?

**Comment by MorayMySoc** [comment]
```No candidates found matching identity: JSON::Fast:ver<0.19>:auth<cpan:TIMOTIMO>```
And it's installing 0.17 again. Must be an issue at my end.

**Comment by MorayMySoc** [comment]
This is an issue with something else and not sure what, so closing this issue. I downloaded JSON::Fast directly from https://raku.land/cpan:TIMOTIMO/JSON::Fast and installed from the download and the upgrade went fine.
