### ISSUE TITLE
Allow --edit with --files-with-matches

### ISSUE THREAD

**Issue by 2colours** [lizmat/App-Rak#47]
Hello,

this is a feature request. Often I find myself wanting to scroll through all Raku-related files but currently it seems one would require to look for specific places in files, and this use-case isn't really supported. I don't know how `--edit` works exactly but I suppose it shouldn't be too hard to add a cursor right at the beginning.

**Comment by lizmat** [comment]
You're right, it shouldn't be.  Will implement this the next time I'm looking at App::Rak again.

**Comment by lizmat** [comment]
Added in the next version of App::Rak
