### ISSUE TITLE
Died at: read from dirhandle failed

### ISSUE THREAD

**Issue by colomon** [lizmat/App-Rak#49]
Hi Liz,
This is probably hopelessly obsolete, but submitting it just in case.  On Windows 11 ARM, Rakudo v2022.07, old-ish App::Rak

[C:\]rak --find vcvars*
A worker in a parallel iteration (hyper or race) initiated here:
  in block  at C:\tools\Rakudo\share\perl6\site\sources\87C318009D8A3D88D89D6A020D2EA3393C39565D (App::Rak) line 978
  in sub show-results at C:\tools\Rakudo\share\perl6\site\sources\87C318009D8A3D88D89D6A020D2EA3393C39565D (App::Rak) line 970
  in sub rak-results at C:\tools\Rakudo\share\perl6\site\sources\87C318009D8A3D88D89D6A020D2EA3393C39565D (App::Rak) line 829
  in sub action-per-line at C:\tools\Rakudo\share\perl6\site\sources\87C318009D8A3D88D89D6A020D2EA3393C39565D (App::Rak) line 3183
  in sub main at C:\tools\Rakudo\share\perl6\site\sources\87C318009D8A3D88D89D6A020D2EA3393C39565D (App::Rak) line 432
  in block <unit> at C:\tools\Rakudo\share\perl6\site\resources\68C3C68C25FF8BA58EEA3E076E7727305545D824 line 3
  in sub MAIN at C:\tools\Rakudo\share\perl6\site\bin\rak line 3
  in block <unit> at C:\tools\Rakudo\share\perl6\site\bin\rak line 1

Died at:
    read from dirhandle failed: 5
      in block  at C:\tools\Rakudo\share\perl6\site\sources\87C318009D8A3D88D89D6A020D2EA3393C39565D (App::Rak) line 978
      in sub show-results at C:\tools\Rakudo\share\perl6\site\sources\87C318009D8A3D88D89D6A020D2EA3393C39565D (App::Rak) line 970
      in sub rak-results at C:\tools\Rakudo\share\perl6\site\sources\87C318009D8A3D88D89D6A020D2EA3393C39565D (App::Rak) line 829
      in sub action-per-line at C:\tools\Rakudo\share\perl6\site\sources\87C318009D8A3D88D89D6A020D2EA3393C39565D (App::Rak) line 3183
      in sub main at C:\tools\Rakudo\share\perl6\site\sources\87C318009D8A3D88D89D6A020D2EA3393C39565D (App::Rak) line 432
      in block <unit> at C:\tools\Rakudo\share\perl6\site\resources\68C3C68C25FF8BA58EEA3E076E7727305545D824 line 3
      in sub MAIN at C:\tools\Rakudo\share\perl6\site\bin\rak line 3
      in block <unit> at C:\tools\Rakudo\share\perl6\site\bin\rak line 1

Only submitting in case it is useful to you.

All the best,
Sol

**Comment by lizmat** [comment]
Pretty sure we don't read from dirs anymore, so closing.

Thanks for the headsup!
