### ISSUE TITLE
Multiline replace

### ISSUE THREAD

**Issue by greenfork** [lizmat/App-Rak#56]
Thank you for this awesome binary!

I have a use case to perform multiline replacements in code, here is an example. For this file `text.txt`:

```
Multi

line
```

I can do matching with `rak --per-file '/Multi\n\nline/' text.txt` but I can't also specify the `--modify-files` option because it complains:

Can only have one action at a time:
'--modify-files' was specified before '--per-file'

Are there any hard-blockers to implement multiline replacement or someone just needs to implement it?

**Comment by lizmat** [comment]
Meh, looks like this needs a re-think of the way `--per-line` and `--per-file` work.  So I doubt a fix for this will be seen today.  Sorry.

**Comment by greenfork** [comment]
Sure, thank for looking into it! My problem is solved by manual labor :( no rush for me right now :^)

**Comment by lizmat** [comment]
[Release 0.3.5](https://raku.land/zef:lizmat/App::Rak?v=0.3.5) fixes this issue.

Thanks again for reporting!
