### ISSUE TITLE
Not call `meh()` from `rak()`

### ISSUE THREAD

**Issue by FCO** [lizmat/App-Rak#6]
Would it be better to not call `meh()` from inside `rak()`? `meh()` calls `exit` and that wouldn’t make it possible to a user using `rak()` on its own module or code to handle that. Could it be an exception?

**Comment by lizmat** [comment]
Good point!   :-)

**Comment by lizmat** [comment]
Actually, I'm thinking of making`rak` return a Supply, and instead of `say` emit to that.  Would that make sense?

**Comment by lizmat** [comment]
Version 0.39 now on zef.  It still calls `meh`, but will `die` instead of `exit` if called as `rak` (well, if the `$*REAL-MEH` environment variable isn't set, but that's an implementation detail).
