### ISSUE TITLE
This type cannot unbox to a native integer: P6opaque, Scalar   in sub want-lines

### ISSUE THREAD

**Issue by jdv** [lizmat/App-Rak#9]
jdv@jdv-lap:~$ cd rakudo
jdv@jdv-lap:~/rakudo$ rak role
docs/announce/2009-02
56:* Existing parameterized roles are now reused instead of creating new ones.

...

src/core.c/Rakudo/Internals/HyperToIterator.pm6
2:my role X::HyperRace::Died {

src/core.c/Rakudo/Internals/HyperWorkStage.pm6
 4:my role Rakudo::Internals::HyperWorkStage {
12:my role Rakudo::Internals::HyperBatcher does Rakudo::Internals::HyperWorkStage {
18:my role Rakudo::Internals::HyperProcessor does Rakudo::Internals::HyperWorkStage {
29:my role Rakudo::Internals::HyperRebatcher does Rakudo::Internals::HyperWorkStage {
39:my role Rakudo::Internals::HyperJoiner does Rakudo::Internals::HyperWorkStage {

src/core.c/Rakudo/Iterator.pm6
  20:# Generic role for iterating over a Blob / Buf.  You need to
  23:our role Blobby does PredictiveIterator {
  58:# Generic role for iterating over a Map / Hash.  You must
  61:our role Mappy does Iterator {
  82:# Generic role for iterating over a Map / Hash that has pairs
  86:our role Mappy-kv-from-pairs does Iterator {
 148:# Generic role for iterating over a >1 dimensional shaped list
 156:our role ShapeBranch does Iterator {
 246:# Generic role for iterating over a >1 dimensional shaped list
 253:# role supplies an optimized .sink-all.
 254:our role ShapeLeaf does Iterator {
 417:my role AllButLastRole {
1788:# XXX TODO: Make this code DRYer by moving common bits to a role,
1790:# signature complains about immutable ints if done in a role, and
1791:# private methods **in roles** are slow, so we duplicated stuff here
2414:my role ListIndex {
2525:# An often occurring use of the Mappy role to generate all of the
2542:# An often occurring use of the Mappy role to generate alternating
2550:# An often occurring use of the Mappy role to generate all of the
4212:# ShapeBranchi roles, but without any additional processing.
This type cannot unbox to a native integer: P6opaque, Scalar
  in sub want-lines at /home/jdv/rakudo/install/share/perl6/site/sources/15066A5E79B965690BA65EFE60430F617F71BC47 (App::Rak) line 991
  in sub rak at /home/jdv/rakudo/install/share/perl6/site/sources/15066A5E79B965690BA65EFE60430F617F71BC47 (App::Rak) line 609
  in block <unit> at /home/jdv/rakudo/install/share/perl6/site/resources/0FFDA62CBE59FDD572FDAC1C05E0FDEB24029390 line 4
  in sub MAIN at /home/jdv/rakudo/install/share/perl6/site/bin/rak line 3
  in block <unit> at /home/jdv/rakudo/install/share/perl6/site/bin/rak line 1

jdv@jdv-lap:~/rakudo$ raku -v
Welcome to Rakudo™ v2022.06-3-gd4e8b671a.
Implementing the Raku® Programming Language v6.d.
Built on MoarVM version 2022.06.
jdv@jdv-lap:~/rakudo$

**Comment by lizmat** [comment]
This is actually a bug in spesh, that I haven't been able to golf yet :-(

**Comment by lizmat** [comment]
Version 0.97 (just uploaded to fez) works around the spesh issue, afaik.  So closing this issue.  Please re-open if I got it wrong
